client_id = "fe1175f2ef15d42402a21456dbeeeea9"
name = "Review Infra"
application_url = "https://reviewinfra.dev"
embedded = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "https://review-infra-api-production.up.railway.app/shopify-webhooks/app-uninstalled"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "https://review-infra-api-production.up.railway.app/shopify-webhooks/orders-create"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "https://review-infra-api-production.up.railway.app/shopify-webhooks/customers-data-request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "https://review-infra-api-production.up.railway.app/shopify-webhooks/customers-redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "https://review-infra-api-production.up.railway.app/shopify-webhooks/shop-redact"

[access_scopes]
scopes = "read_products,write_script_tags,read_orders,read_customers"
optional_scopes = []
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://review-infra-api-production.up.railway.app/shopify/auth/callback"
]
